### ISSUE TITLE
v0.0.5 - To-Do List

### ISSUE THREAD

**Issue by Kenzzer** [Kenzzer/VSH-Rewrite#4]
- [x] Rework Vagineer Reverse rage ability
- [x] Implement rage & super rage effects indicator
> - [x] Flash particle upon super rage activation
> - [x] Stars aura particle for rage & super rage
> - [x] Self sound indicator for rage & super rage
> - [x] Global sound for super rage activation
- [ ] Complete the classes help panels
- [ ] Dev comments the code
- [ ] Allow players to enable special rounds through items
